# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://175.178.94.224:3306/ybyyhis_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: Frost
    password: chen6185653
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl